package com.game.pokemon;

/**
 * enum che definisce i tipi di entità presenti nel gioco
 */
public enum PokemonTypes {
    PLAYER, SPAWNPOINT,
    RINGGROUDON, RINGLAPRAS,
    GROUDON, SPAWNGROUDON,
    LAPRAS, SPAWNLAPRAS,
    OGGETTOSOLIDO,
    SAFFI, SPAWNSAFFI,
    BIRAL, SPAWNBIRAL,
    DISTEFANO, SPAWNDISTEFANO,
    MANCINO, SPAWNMANCINO,
    ZUCCON, SPAWNZUCCON,    // Solo frase da decidere
    FUNES, SPAWNFUNES,
    SANDI, SPAWNSANDI,
    PESENTI, SPAWNPESENTI,
    PENZO, SPAWNPENZO,
    PAGAN, SPAWNPAGAN,
    STEVE, SPAWNSTEVE,  //VUOI GIOCARE A LOL?
}
