package com.game.pokemon;

public enum PokemonTypes {
    PLAYER, SPAWNPOINT,
    RINGGROUDON,
    GROUDON, SPAWNGROUDON,
    OGGETTOSOLIDO,
    SAFFI, SPAWNSAFFI,
    BIRAL, SPAWNBIRAL,
    DISTEFANO, SPAWNDISTEFANO
}
