package com.game.pokemon;

public enum PokemonTypes {
    PLAYER, SPAWNPOINT,
    RINGGROUDON,
    GROUDON, SPAWNGROUDON,
    OGGETTOSOLIDO,
    SAFFI, SPAWNSAFFI,
    BIRAL, SPAWNBIRAL,  //POPA...  ESSERE INUTILE...
    DISTEFANO, SPAWNDISTEFANO,  //HAI FATTO I COMPITI?
    MANCINO, SPAWNMANCINO,
    ZUCCON, SPAWNZUCCON,    //
    FUNES, SPAWNFUNES,  //APRITE PACKET TRACER
    SANDI, SPAWNSANDI,  //COME SCUSA?!?!
    PESENTI, SPAWNPESENTI, //NON HO ANCORA CORRETTO LE VERIFICHE
    PENZO, SPAWNPENZO,  //HAI GIUSTIFICATO?!
    PAGAN, SPAWNPAGAN,  //HAI FATTO IL RISCALDAMENTO?
    STEVE, SPAWNSTEVE,  //VUOI GIOCARE A LOL?
}
